"""empty message

Revision ID: b8ff17f0b42e
Revises: 2d8884a16095
Create Date: 2024-03-12 19:49:54.226860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ff17f0b42e'
down_revision: Union[str, None] = '2d8884a16095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('Actor', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('Actor', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.drop_column('Actor', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('Actor', 'middle_name')
    op.drop_column('Actor', 'last_name')
    op.drop_column('Actor', 'first_name')
    # ### end Alembic commands ###
