"""empty message

Revision ID: 29a18eeb4073
Revises: b8ff17f0b42e
Create Date: 2024-03-19 19:40:23.656251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a18eeb4073'
down_revision: Union[str, None] = 'b8ff17f0b42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Actor', 'bdate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('bdate', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
