# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(804, 522)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 350, 55, 16))
        self.label.setObjectName("label")
        self.label_answer = QtWidgets.QLabel(Form)
        self.label_answer.setGeometry(QtCore.QRect(170, 340, 271, 41))
        self.label_answer.setText("")
        self.label_answer.setObjectName("label_answer")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(50, 60, 80, 76))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_1_red = QtWidgets.QRadioButton(self.widget)
        self.radioButton_1_red.setObjectName("radioButton_1_red")
        self.verticalLayout.addWidget(self.radioButton_1_red)
        self.radioButton_1_blue = QtWidgets.QRadioButton(self.widget)
        self.radioButton_1_blue.setObjectName("radioButton_1_blue")
        self.verticalLayout.addWidget(self.radioButton_1_blue)
        self.radioButton_1_green = QtWidgets.QRadioButton(self.widget)
        self.radioButton_1_green.setObjectName("radioButton_1_green")
        self.verticalLayout.addWidget(self.radioButton_1_green)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(240, 60, 80, 76))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_2_red = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_2_red.setObjectName("radioButton_2_red")
        self.verticalLayout_2.addWidget(self.radioButton_2_red)
        self.radioButton_2_blue = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_2_blue.setObjectName("radioButton_2_blue")
        self.verticalLayout_2.addWidget(self.radioButton_2_blue)
        self.radioButton_2_green = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_2_green.setObjectName("radioButton_2_green")
        self.verticalLayout_2.addWidget(self.radioButton_2_green)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(450, 60, 80, 76))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_3_red = QtWidgets.QRadioButton(self.widget2)
        self.radioButton_3_red.setObjectName("radioButton_3_red")
        self.verticalLayout_3.addWidget(self.radioButton_3_red)
        self.radioButton_3_blue = QtWidgets.QRadioButton(self.widget2)
        self.radioButton_3_blue.setObjectName("radioButton_3_blue")
        self.verticalLayout_3.addWidget(self.radioButton_3_blue)
        self.radioButton_3_green = QtWidgets.QRadioButton(self.widget2)
        self.radioButton_3_green.setObjectName("radioButton_3_green")
        self.verticalLayout_3.addWidget(self.radioButton_3_green)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(490, 340, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Ответ:"))
        self.radioButton_1_red.setText(_translate("Form", "Красный"))
        self.radioButton_1_blue.setText(_translate("Form", "Синий"))
        self.radioButton_1_green.setText(_translate("Form", "Зеленый"))
        self.radioButton_2_red.setText(_translate("Form", "Красный"))
        self.radioButton_2_blue.setText(_translate("Form", "Синий"))
        self.radioButton_2_green.setText(_translate("Form", "Зеленый"))
        self.radioButton_3_red.setText(_translate("Form", "Красный"))
        self.radioButton_3_blue.setText(_translate("Form", "Синий"))
        self.radioButton_3_green.setText(_translate("Form", "Зеленый"))
        self.pushButton.setText(_translate("Form", "Ok"))
