"""empty message

Revision ID: 1e592d91d802
Revises: 29a18eeb4073
Create Date: 2024-03-19 19:40:48.153260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e592d91d802'
down_revision: Union[str, None] = '29a18eeb4073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('bdate', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Actor', 'bdate')
    # ### end Alembic commands ###
